### ISSUE TITLE
Creation of song parts does not appear to happen in parallel.

### ISSUE THREAD

**Issue by seanmtracey** [Choirless/choirlessapi#31]
## Problem
When trying to add two or more parts to a newly created song in a choir on the `/choir/songPartName` endpoint the service fails and returns a `404` status code. However, if I introduce an artificial delay of more than 100ms in between each request they complete succesfuly and return

## Expected Behaviour
When one or more parts are being added to a song simultaneously, they should be added to the song and return a `200` status

## Actual behaviour
Without a delay in between the requests, the second and subsequent addition fails to be added to the database

**Comment by seanmtracey** [comment]
Suspect it might be because both or more are referencing the same revision number when writing to the database, which would no longer be valid after the first write.

**Comment by glynnbird** [comment]
Correct. Cloudant modify the same document simultaneously in 5 different ways. Can't get around that. It worked originally because it was a flat array supplied in the `POST /choir/song` and point.

If you have several partNames to add at once I suggest I create a new endping:

## POST /choir/songPartNames

Allows multiple partNames to be added (not edited) at once.

Paramters

- choirId
- songId
- partNames - a flat array of partNames which is converted into `[ { partNameId: '<uuid>', name: '<partName>}]` format

OR

we allow the `partNames` array to be supplied in `POST /choir/song` as before, but letting _it_ convert the partNames array into an array of objects with their own id.

---------

Up to you: the decision would depend on whether the front end wants to be able to create a song (without the partNames and add them later) or to create the song and partNames in one API call.

**Comment by seanmtracey** [comment]
Cool, that makes sense. Let's put a pin in it for another time, I can make the application server create the song parts in sequence rather than simultaneously and this isn't a showstopper right now - just wanted to make sure I wasn't being incredibly dense again 😅

**Comment by glynnbird** [comment]
If, when creating the song initially, you supply a flat array of partNames `partNames: ['alto','tenor','soprano']`, it will convert them into an array of objects. They can then be edited with `POST /choir/songPartName` & `DELETE /choir/songPartName`

i.e. no need to call  `POST /choir/songPartName` multiple times on song creation
