### ISSUE TITLE
Password reset tokens

### ISSUE THREAD

**Issue by seanmtracey** [Choirless/choirlessapi#45]
Right now, we have all the functionality we need to offer users to reset their passwords if they've forgotten them - except a way to confirm that the person who has received and followed the link an email is the right person.

If we had an API endpoint which could function similar to invitations (tied to an account, expires after a certain time) we can implement a password reset in the application-server and mail API

**Comment by glynnbird** [comment]
I'll look at this tomorrow 👍

**Comment by glynnbird** [comment]
A couple of things going on here. If the use _isn't_ logged in and they click a "reset" password button, you're going to need an API to find a user's `userId` from their email address:

## GET /user/byemail

Parameters:

- `email` - the email address of the user to be fetched

------

Then I suggest I extend the `POST /invitation` API to allow you to store the `userId` of the user who is asking to reset their password, and like other invitations it will expire in a few days. So you'd do

```
POST /invitation`
```

passing the `userId` of the user who is asking to reset their password. The invitation id becomes the token you put in their email.

-----

When the user clicks on the email you call `GET /invitation` to get the details of the invitation which will include the `userId`. You can then call `POST /user` to overwrite their password with something you communicate with them, or something they enter in your UI. For belt & braces, you can then call `DELETE /invitation` to kill the invitation so that the token can't be used again.

------

What do you think @seanmtracey ?

**Comment by seanmtracey** [comment]
Yup, that all works. I'm a tad worried about invitations becoming a generic endpoint for generating temporary, time sensitive links that only have meaning when combined with the front-end though. That said, I'm a pragmatist, I can work with this :)

**Comment by glynnbird** [comment]
@seanmtracey yeah. `invitations` could be called `tokens` - but let's leave the name as it is for now. We can change later if it upsets us.

**Comment by seanmtracey** [comment]
Sounds like a plan 👍
